version: '3'

services:
  rithm-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/rithm-pypy:14.4.0
    volumes:
      - ./pyproject.toml:/opt/rithm/pyproject.toml
      - ./README.md:/opt/rithm/README.md
      - ./rithm:/opt/rithm/rithm
      - ./setup.py:/opt/rithm/setup.py
      - ./tests:/opt/rithm/tests
    entrypoint: pytest
