version: '3'

services:
  rithm-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/rithm-cpython:14.6.0-alpha
    volumes:
      - ./Cargo.toml:/opt/rithm/Cargo.toml
      - ./pyproject.toml:/opt/rithm/pyproject.toml
      - ./README.md:/opt/rithm/README.md
      - ./rithm:/opt/rithm/rithm
      - ./rust-toolchain.toml:/opt/rithm/rust-toolchain.toml
      - ./setup.py:/opt/rithm/setup.py
      - ./src:/opt/rithm/src
      - ./tests:/opt/rithm/tests
    entrypoint: pytest
